version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - database
  database:
    image: hypriot/rpi-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Cherfianadir2022@
      - MYSQL_DATABASE=iot_air_quality
    volumes:
      - mysql-db:/var/lib/mysql
      - ./:/var/lib/mysql
    mqtt:
      image: mjenz/rpi-mosquitto
      environment:
        - MYSQL_USER=iot_enst
        - MYSQL_PASSWORD=cherfianadir
    node-red:
      image: hypriot/rpi-node
      depends_on: mqtt
      
volumes:
  mysql-db: